name: "Publish in Docker"
description: "Build a container image and pushes it to a Docker registry"

inputs:
  registry_username:
    description: "Username for image registry"
    required: true
  registry_password:
    description: "Password for image registry"
    required: true
  image_name:
    description: "Name of the image to push"
    required: true
  tag:
    Description: "How to tag image. Default: latest"

runs:
  using: "composite"
  steps:
    - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
      
    - name: Login to the registry
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          username: ${{ inputs.registry_username }}
          password: ${{ inputs.registry_password }}

    - name: Set the tag
      shell: bash
      run: |
        if [ -z "${{inputs.tag}}" ]
        then
          echo "final_tag=latest" >> $GITHUB_ENV
        else
          echo "final_tag=${{inputs.tag}}" >> $GITHUB_ENV
        fi

    - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          push: true
          tags: ${{inputs.registry_username}}/${{inputs.image_name}}:${{}}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

